[pytest]
# Default test directory
testpaths = Framework

# Default options (applied automatically)
addopts =
    --html=reports/pytest_report.html
    --alluredir=reports/allure-results
    -v

# Optional: Generate report on each test (streaming)
#generate_report_on_test = True