[pytest]
# Default test directory
testpaths = Framework

# Allure Reports (applied automatically)
addopts =
    --html=reports/pytest_report.html
    --alluredir=reports/allure-results
    -v

#HTML Reports (If needed HTML use this if allure use above for reports)
#addopts =
#    --html=reports/pytest_report.html
#    --self-contained-html
#    -v

# Optional: Generate report on each test (streaming)
#generate_report_on_test = True